/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2016 JiaweiMao
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software
 * and associated documentation files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or
 * substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

/**
 * GUI applications are event-driven. An application reacts to different event types which are generated
 * during its lifetime. Events are generated by a user (a mouse click), an application (a timer), or the system(a clock).
 *
 * An event is a notification about a change. it encapsulates the state changes in the event source. Registered
 * event filters and event handlers within the application receive the event and provide a response.
 *
 * Every event in JavaFX has three properties:
 * - Event source
 * - Event target
 * - Event type
 *
 * Event source is the object whose state changes; it generates events. Event target is the destination of the an
 * event. Event type provides additional classification to events of the same Event class.
 *
 * Event source object delegates the task of handling an event to the event handler. When the event occurs, the
 * event source creates an event object and sends it to each registered handler.
 */
package trail.jgui.javafx.event;