/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2016 JiaweiMao
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software
 * and associated documentation files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or
 * substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

package trail.jgui.javafx;

import javafx.application.Application;
import javafx.stage.Stage;

/**
 * The launch() method detects that it is called from the run() method of the MyJavaFXApp$1 class.
 * MyJavaFXApp$1 class ia an enonymous inner class generated by the compiler, which is a subclas of the Object class,
 * not the Application class, and it implements the Runnable interface.
 *
 * @author JiaweiMao
 * @version 1.0.0
 * @date 2016.12.19, 3:49 PM
 */
public class MyJavaFXApp extends Application {

    public static void main(String[] args) {
        Thread t = new Thread(new Runnable() {
            @Override public void run() {
                Application.launch(args);
            }
        });
        t.start();
    }

    @Override public void start(Stage primaryStage) throws Exception {

    }
}
